---
title: "RStudio Conference Talk 2022"
description: |
  Becoming creative: How I designed a quilt with R.
author:
  - name: Alice Walsh
    url: {}
date: 2022-07-26
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

*Update: The talk recording is now available online on the [conference website](https://www.rstudio.com/conference/2022/talks/quilting-in-r-becoming-creative/).*

I am excited to attend my first in person R-centric conference this year with RStudio::conf. 

I am even more excited to get the opportunity to participate as a speaker.

Link to [slides](./slides/index.html)

Abstract

> When someone asks about essential skills for data careers, I often hear responses like R, Python, and machine learning. However, I argue that creativity is an underrated skill that you can and should practice. In this talk, I want to tell you a story about a project I did to stretch my creative brain and use my favorite tool, R. I designed a quilt in R using generative art ideas. Then I created individual blocks that make up the larger design. I used foundation paper piecing, a method that allows for intricate designs but has geometrical constraints. I hope my talk will entertain and inspire folks to exercise their creative muscles to improve their performance and enjoyment of their day jobs.


Thanks to the organizers for having me and making this a very positive experience!
